apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mx09lporq-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-4a680e644b.8nnn.p3.openshiftapps.com/rhtap/rhtap-qe:68e3f860fafd5c519caa8dae96f98988e3ccb922@sha256:0783ba2e14e54a6464f6ec664a82e29aee6c4e31faab62c7ee86bc6bdf227cc5
          name: container-image
